import React, { useState, useEffect } from 'react';
import { 
  Mail, Users, Send, Settings, RefreshCw, CheckCircle, 
  AlertTriangle, ShieldCheck, Info, FileText, Check, Search, Filter 
} from 'lucide-react';

interface RegisteredUser {
  id: string;
  type: "shop_created" | "staff_joined";
  businessName: string;
  name: string;
  email: string;
  phone: string;
  role: string;
  date: string;
  shopCode: string;
}

interface SentEmail {
  id: string;
  to: string[];
  subject: string;
  body: string;
  date: string;
  status: "sent" | "logged_only" | "failed_smtp_logged";
  error?: string;
  info?: string;
  isHtml: boolean;
}

const EMAIL_PRESETS = [
  {
    id: 'newsletter',
    name: '🌟 General Newsletter',
    subject: 'ShopLedger Hub: Tips to Scale Your Shop Profits 📈',
    body: `Hi [Name],

Welcome to this month's ShopLedger newsletter! 

We have added incredible new offline-first features to help you track your sales and expenses with zero hassle. Here are 3 quick tips to make the most of ShopLedger:
1. Lock your ledger with personal PINs for Managers and Salespersons.
2. Keep your stock lists updated to get automatically predicted low-stock alerts.
3. Export weekly backups to protect your sales logs.

Thank you for choosing ShopLedger to run your shop!

Best regards,
The ShopLedger Team`
  },
  {
    id: 'update',
    name: '🚀 Product Update',
    subject: 'ShopLedger Update: Interactive Charts & AI Insights 🤖',
    body: `Hi [Name],

We are thrilled to announce that ShopLedger v2.0 is now live!

In this update:
- **AI Business Analyst**: Get smart insights, low-stock warnings, and cash flow advice automatically generated by Google Gemini.
- **Improved Settings Tab**: The main shop owners now have strict controls over pin locked features and directory profiles.
- **Enhanced PDF Receipts**: Clean, minimal receipt generation for customer receipts.

Log in to [BusinessName] today to explore the new capabilities!

Best regards,
The ShopLedger Team`
  },
  {
    id: 'billing',
    name: '💳 Billing & License Update',
    subject: 'ShopLedger Premium: Billing Options & Subscription Notice 🧾',
    body: `Hi [Name],

This is a professional notification regarding your ShopLedger account for [BusinessName].

In order to keep bringing you lightning-fast offline syncs and advanced analytics, we will be introducing optional premium subscription tiers starting next month. 
- **Free Tier**: Unlimited local ledgers, standard sales & expenses, local backup exports.
- **Premium Tier**: Multiple branch synchronizations, priority SMS alerts, and deep AI insights.

No actions are required from you today. Your shop ledger will remain completely active and safe.

For questions, feel free to contact us at support@shopledger.com.

Best regards,
ShopLedger Billing Services`
  }
];

export default function AppOwnerHub() {
  const [users, setUsers] = useState<RegisteredUser[]>([]);
  const [emails, setEmails] = useState<SentEmail[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const [syncing, setSyncing] = useState<boolean>(false);
  
  // Selection
  const [selectedUserIds, setSelectedUserIds] = useState<string[]>([]);
  
  // Search & Filter
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [typeFilter, setTypeFilter] = useState<"all" | "shop" | "staff">("all");
  
  // Email Form
  const [emailSubject, setEmailSubject] = useState<string>("");
  const [emailBody, setEmailBody] = useState<string>("");
  const [isHtml, setIsHtml] = useState<boolean>(false);
  const [sendSuccess, setSendSuccess] = useState<string>("");
  const [sendError, setSendError] = useState<string>("");
  const [sending, setSending] = useState<boolean>(false);

  // Load registered users and sent email logs from the server
  const fetchHubData = async () => {
    setSyncing(true);
    try {
      const usersRes = await fetch('/api/admin/users');
      const usersData = await usersRes.json();
      if (usersData.success) {
        setUsers(usersData.users);
      }

      const emailsRes = await fetch('/api/admin/emails');
      const emailsData = await emailsRes.json();
      if (emailsData.success) {
        setEmails(emailsData.emails);
      }
    } catch (err) {
      console.error("Failed to load Hub data from server:", err);
    } finally {
      setSyncing(false);
    }
  };

  useEffect(() => {
    fetchHubData();
  }, []);

  // Filter users
  const filteredUsers = users.filter(u => {
    const query = searchQuery.toLowerCase();
    const matchesSearch = 
      u.name.toLowerCase().includes(query) || 
      (u.email && u.email.toLowerCase().includes(query)) || 
      u.businessName.toLowerCase().includes(query);
    
    const matchesType = 
      typeFilter === "all" || 
      (typeFilter === "shop" && u.type === "shop_created") ||
      (typeFilter === "staff" && u.type === "staff_joined");

    return matchesSearch && matchesType;
  });

  // Toggle user selection
  const handleToggleSelectUser = (id: string) => {
    if (selectedUserIds.includes(id)) {
      setSelectedUserIds(selectedUserIds.filter(uid => uid !== id));
    } else {
      setSelectedUserIds([...selectedUserIds, id]);
    }
  };

  const handleSelectAllFiltered = () => {
    const allFilteredIds = filteredUsers.map(u => u.id);
    const allSelected = allFilteredIds.every(id => selectedUserIds.includes(id));
    
    if (allSelected) {
      // Deselect filtered users
      setSelectedUserIds(selectedUserIds.filter(id => !allFilteredIds.includes(id)));
    } else {
      // Select all filtered users (union)
      setSelectedUserIds(Array.from(new Set([...selectedUserIds, ...allFilteredIds])));
    }
  };

  // Apply Email Preset
  const handleApplyPreset = (presetId: string) => {
    const preset = EMAIL_PRESETS.find(p => p.id === presetId);
    if (preset) {
      setEmailSubject(preset.subject);
      
      // If we have a single user selected, customize their name placeholder
      if (selectedUserIds.length === 1) {
        const selectedUser = users.find(u => u.id === selectedUserIds[0]);
        if (selectedUser) {
          let customBody = preset.body
            .replace(/\[Name\]/g, selectedUser.name)
            .replace(/\[BusinessName\]/g, selectedUser.businessName);
          setEmailBody(customBody);
          return;
        }
      }
      
      // Otherwise keep default generic markers
      setEmailBody(preset.body.replace(/\[Name\]/g, 'Valued Partner').replace(/\[BusinessName\]/g, 'your shop'));
    }
  };

  // Send Email Handler
  const handleSendEmail = async (e: React.FormEvent) => {
    e.preventDefault();
    setSendSuccess("");
    setSendError("");
    
    if (selectedUserIds.length === 0) {
      setSendError("Please select at least one recipient user.");
      return;
    }
    if (!emailSubject.trim()) {
      setSendError("Please specify a subject.");
      return;
    }
    if (!emailBody.trim()) {
      setSendError("Please enter email content.");
      return;
    }

    // Map recipient IDs to emails
    const recipients = users
      .filter(u => selectedUserIds.includes(u.id))
      .map(u => u.email || `${u.name.toLowerCase().replace(/\s+/g, '')}@shopledger-mock.com`) // fallback elegant mock if email is blank
      .filter(Boolean);

    setSending(true);
    try {
      const response = await fetch('/api/admin/send-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: recipients,
          subject: emailSubject,
          body: emailBody,
          isHtml: isHtml
        })
      });

      const resData = await response.json();
      if (resData.success) {
        setSendSuccess(resData.message);
        // Reset compose
        setEmailSubject("");
        setEmailBody("");
        setSelectedUserIds([]);
        // Refresh logs
        fetchHubData();
      } else {
        setSendError(resData.error || "Failed to send newsletter email.");
      }
    } catch (err: any) {
      setSendError(err.message || "Network error occurred while delivering email.");
    } finally {
      setSending(false);
    }
  };

  return (
    <div className="space-y-6 animate-fade-in max-w-4xl mx-auto pb-16">
      
      {/* Header Info Panel */}
      <div className="bg-teal-950 text-white rounded-[24px] p-6 border border-teal-900/60 shadow-xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-black uppercase tracking-widest bg-emerald-500 text-teal-950 px-2.5 py-1 rounded-md">App Owner Hub</span>
            <span className="text-[10px] text-teal-300 font-bold bg-teal-900/50 px-2 py-1 rounded-md flex items-center gap-1 border border-teal-850">
              <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" /> Authorized Admin Mode
            </span>
          </div>
          <h2 className="text-xl font-black text-white mt-2 tracking-tight">Software Client Registry & Email updates</h2>
          <p className="text-xs text-teal-200 mt-1 font-medium max-w-xl">
            Monitor new registered shops/users of your ShopLedger platform. Send mass updates, newsletters, product change logs, and billing statements to clients.
          </p>
        </div>
        
        <button
          onClick={fetchHubData}
          disabled={syncing}
          className="px-4 py-2.5 bg-teal-900 hover:bg-teal-850 text-emerald-300 rounded-full border border-teal-800 transition-all text-xs font-bold flex items-center gap-2 cursor-pointer shadow-md disabled:opacity-50 shrink-0"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${syncing ? 'animate-spin text-emerald-400' : ''}`} />
          {syncing ? "Refreshing Registry..." : "Refresh Database"}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Side: Users Directory */}
        <div className="lg:col-span-7 bg-white border border-gray-100 rounded-[24px] p-5 shadow-sm space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-gray-50">
            <div>
              <h3 className="text-sm font-bold text-gray-900 flex items-center gap-2">
                <Users className="w-4 h-4 text-teal-600" />
                Registered Client Registry ({users.length})
              </h3>
              <p className="text-[11px] text-gray-500 font-semibold">Select recipients below to draft mass updates.</p>
            </div>
            
            {/* Type Filters */}
            <div className="flex bg-gray-50 border border-gray-150 p-1 rounded-xl text-[10px] font-bold">
              <button 
                onClick={() => setTypeFilter("all")}
                className={`px-2.5 py-1 rounded-lg transition-all ${typeFilter === 'all' ? 'bg-white text-teal-900 shadow-sm' : 'text-gray-400 hover:text-gray-600'}`}
              >All</button>
              <button 
                onClick={() => setTypeFilter("shop")}
                className={`px-2.5 py-1 rounded-lg transition-all ${typeFilter === 'shop' ? 'bg-white text-teal-900 shadow-sm' : 'text-gray-400 hover:text-gray-600'}`}
              >Shops</button>
              <button 
                onClick={() => setTypeFilter("staff")}
                className={`px-2.5 py-1 rounded-lg transition-all ${typeFilter === 'staff' ? 'bg-white text-teal-900 shadow-sm' : 'text-gray-400 hover:text-gray-600'}`}
              >Staff</button>
            </div>
          </div>

          {/* Search Controls */}
          <div className="relative">
            <Search className="w-3.5 h-3.5 text-gray-450 absolute left-3.5 top-3" />
            <input 
              type="text" 
              placeholder="Search by client name, shop brand, or email..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full h-9 pl-9 pr-4 bg-gray-50 border border-gray-100 rounded-xl text-xs font-semibold text-gray-700 outline-none focus:border-teal-500 transition-all placeholder:text-gray-400"
            />
          </div>

          {/* Batch Selector */}
          {filteredUsers.length > 0 && (
            <div className="flex justify-between items-center bg-teal-50/50 px-3 py-2 rounded-xl border border-teal-100/30 text-[11px]">
              <span className="font-bold text-teal-900">
                {selectedUserIds.length} of {filteredUsers.length} clients selected
              </span>
              <button 
                onClick={handleSelectAllFiltered}
                className="text-teal-700 hover:text-teal-900 font-black cursor-pointer uppercase tracking-wider text-[10px]"
              >
                {filteredUsers.every(u => selectedUserIds.includes(u.id)) ? "Deselect All" : "Select All Listed"}
              </button>
            </div>
          )}

          {/* User List */}
          <div className="space-y-2 max-h-[380px] overflow-y-auto pr-1">
            {filteredUsers.length === 0 ? (
              <div className="text-center py-10 space-y-2">
                <Users className="w-8 h-8 text-gray-300 mx-auto" />
                <p className="text-xs text-gray-400 font-semibold">No registered users matched your criteria.</p>
              </div>
            ) : (
              filteredUsers.map(user => {
                const isSelected = selectedUserIds.includes(user.id);
                const isShop = user.type === "shop_created";
                
                return (
                  <div 
                    key={user.id}
                    onClick={() => handleToggleSelectUser(user.id)}
                    className={`p-3.5 rounded-2xl border transition-all flex items-start gap-3 cursor-pointer ${
                      isSelected 
                        ? 'bg-teal-50/40 border-teal-200 shadow-sm' 
                        : 'bg-gray-50 border-gray-100 hover:border-gray-250'
                    }`}
                  >
                    {/* Checkbox */}
                    <div className={`w-4 h-4 rounded-md border flex items-center justify-center shrink-0 mt-1 transition-all ${
                      isSelected 
                        ? 'bg-teal-600 border-teal-600 text-white' 
                        : 'border-gray-300 bg-white'
                    }`}>
                      {isSelected && <Check className="w-3 h-3 stroke-[3]" />}
                    </div>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-extrabold text-xs text-gray-900">{user.name}</span>
                        <span className={`text-[8px] font-black uppercase px-1.5 py-0.5 rounded-full tracking-wider border ${
                          isShop 
                            ? 'bg-emerald-50 text-emerald-700 border-emerald-150' 
                            : 'bg-teal-50 text-teal-700 border-teal-150'
                        }`}>
                          {isShop ? "Shop Owner" : `Staff - ${user.role}`}
                        </span>
                      </div>

                      <div className="mt-1 flex items-center gap-2 text-[10px] text-gray-500 font-semibold flex-wrap">
                        <span className="text-teal-950 bg-teal-50 px-1.5 py-0.5 rounded font-black">{user.businessName}</span>
                        {user.email ? (
                          <span className="truncate">{user.email}</span>
                        ) : (
                          <span className="text-gray-400 italic">No email saved</span>
                        )}
                        {user.phone && <span className="text-gray-400">• {user.phone}</span>}
                      </div>

                      <p className="text-[9px] text-gray-400 mt-1.5 font-bold">
                        Registered: {new Date(user.date).toLocaleDateString()} at {new Date(user.date).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                        {user.shopCode && ` • Shop Code: ${user.shopCode}`}
                      </p>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* Right Side: Email Mass Update Composer */}
        <div className="lg:col-span-5 bg-white border border-gray-100 rounded-[24px] p-5 shadow-sm space-y-4 flex flex-col justify-between">
          <div className="space-y-4">
            <div>
              <h3 className="text-sm font-bold text-gray-900 flex items-center gap-2">
                <Mail className="w-4 h-4 text-teal-600" />
                Draft Mass Newsletter
              </h3>
              <p className="text-[11px] text-gray-500 font-semibold">Write and send emails to selected registered accounts.</p>
            </div>

            {/* Template Presets */}
            <div className="space-y-1.5">
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider">Quick Newsletter Presets</label>
              <div className="grid grid-cols-1 gap-1.5">
                {EMAIL_PRESETS.map(preset => (
                  <button
                    key={preset.id}
                    type="button"
                    onClick={() => handleApplyPreset(preset.id)}
                    className="w-full text-left p-2 bg-gray-50 hover:bg-gray-100 border border-gray-150 rounded-xl text-xs font-semibold text-gray-700 transition-all cursor-pointer flex justify-between items-center"
                  >
                    <span>{preset.name}</span>
                    <span className="text-[9px] text-gray-400 font-bold uppercase tracking-wider">Load</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Compose Form */}
            <form onSubmit={handleSendEmail} className="space-y-3.5">
              {sendSuccess && (
                <div className="p-3 bg-emerald-50 text-emerald-850 rounded-xl border border-emerald-150 text-[11px] font-semibold leading-normal flex items-start gap-2">
                  <CheckCircle className="w-4 h-4 text-emerald-600 mt-0.5 shrink-0" />
                  <div>{sendSuccess}</div>
                </div>
              )}
              {sendError && (
                <div className="p-3 bg-rose-50 text-rose-850 rounded-xl border border-rose-150 text-[11px] font-semibold leading-normal flex items-start gap-2">
                  <AlertTriangle className="w-4 h-4 text-rose-600 mt-0.5 shrink-0" />
                  <div>{sendError}</div>
                </div>
              )}

              {/* Subject */}
              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1">Email Subject</label>
                <input 
                  type="text" 
                  required
                  placeholder="e.g. Important shop system updates..."
                  value={emailSubject}
                  onChange={(e) => setEmailSubject(e.target.value)}
                  className="w-full h-10 px-4 bg-gray-50 border border-gray-100 rounded-xl text-xs font-semibold text-gray-700 outline-none focus:border-teal-500 transition-all"
                />
              </div>

              {/* Message */}
              <div>
                <div className="flex justify-between items-center mb-1">
                  <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider">Email Body</label>
                  <span className="text-[9px] text-gray-400 font-bold">Use [Name] or [BusinessName]</span>
                </div>
                <textarea 
                  required
                  rows={8}
                  placeholder="Dear [Name], write your mass newsletter or billing notifications here..."
                  value={emailBody}
                  onChange={(e) => setEmailBody(e.target.value)}
                  className="w-full p-4 bg-gray-50 border border-gray-100 rounded-xl text-xs font-semibold text-gray-700 outline-none focus:border-teal-500 transition-all font-sans leading-relaxed resize-none"
                />
              </div>

              {/* HTML Flag */}
              <div className="flex items-center gap-2">
                <input 
                  type="checkbox" 
                  id="html-flag"
                  checked={isHtml}
                  onChange={(e) => setIsHtml(e.target.checked)}
                  className="w-3.5 h-3.5 border-gray-300 rounded text-teal-600 outline-none"
                />
                <label htmlFor="html-flag" className="text-[11px] font-bold text-gray-500 cursor-pointer">
                  Send as Rich HTML Email
                </label>
              </div>

              {/* Send Button */}
              <button
                type="submit"
                disabled={sending || selectedUserIds.length === 0}
                className="w-full h-10 bg-teal-950 hover:bg-teal-900 disabled:bg-gray-200 disabled:text-gray-400 disabled:cursor-not-allowed text-white text-xs font-bold rounded-full transition-all flex items-center justify-center gap-2 cursor-pointer shadow-md"
              >
                <Send className="w-3.5 h-3.5" />
                {sending ? "Delivering Updates..." : `Send Newsletter to ${selectedUserIds.length} Recipients`}
              </button>
            </form>
          </div>
        </div>

      </div>

      {/* SMTP Environment Setup Information & Logs */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Environment setup warning info */}
        <div className="bg-gray-50 border border-gray-100 rounded-[24px] p-5 space-y-3.5">
          <h4 className="text-xs font-bold text-teal-950 uppercase tracking-wider flex items-center gap-1.5">
            <Settings className="w-4 h-4 text-teal-700" />
            Configuring Real Email Deliverability
          </h4>
          <p className="text-[11px] text-gray-600 font-semibold leading-relaxed">
            By default, if SMTP variables are not set in your environmental variables, the system runs in **Log and Queue Mode**. All emails you dispatch are fully structured, tracked, and stored in the server registry, but are not actively sent to real-world inbox services.
          </p>
          <div className="p-3.5 bg-amber-50/70 border border-amber-100 rounded-2xl space-y-2">
            <span className="text-[10px] font-extrabold text-amber-900 uppercase tracking-wider flex items-center gap-1">
              <Info className="w-3.5 h-3.5 text-amber-600" />
              How to enable real mail servers:
            </span>
            <p className="text-[10px] text-amber-850 font-semibold leading-relaxed">
              Add SMTP credentials to your workspace secrets in AI Studio or your local <code className="bg-amber-100/60 px-1 py-0.5 rounded font-mono text-[9px]">.env</code> file:
            </p>
            <div className="font-mono text-[9px] bg-white border border-amber-200/50 p-2.5 rounded-xl space-y-0.5 text-amber-950 select-all overflow-x-auto leading-relaxed">
              <div>SMTP_HOST="smtp.mailgun.org" (or Gmail, Sendgrid)</div>
              <div>SMTP_PORT="587"</div>
              <div>SMTP_USER="postmaster@yourdomain.com"</div>
              <div>SMTP_PASS="your-secure-password"</div>
              <div>SMTP_FROM="ShopLedger &lt;news@yourdomain.com&gt;"</div>
            </div>
          </div>
        </div>

        {/* Delivery Logs */}
        <div className="bg-white border border-gray-100 rounded-[24px] p-5 space-y-4 shadow-sm flex flex-col justify-between">
          <div>
            <h4 className="text-xs font-bold text-gray-900 uppercase tracking-wider flex items-center gap-1.5">
              <FileText className="w-4 h-4 text-teal-600" />
              Sent Updates & billing delivery history ({emails.length})
            </h4>
            <p className="text-[11px] text-gray-500 font-semibold mb-3">Audit trail of outgoing mass updates.</p>
            
            <div className="space-y-2 max-h-[170px] overflow-y-auto pr-1">
              {emails.length === 0 ? (
                <div className="text-center py-6 text-[11px] text-gray-400 font-semibold italic">
                  No newsletters have been logged or sent yet.
                </div>
              ) : (
                [...emails].reverse().map(email => {
                  const isSent = email.status === "sent";
                  return (
                    <div key={email.id} className="p-3 bg-gray-50 border border-gray-100 rounded-xl space-y-1">
                      <div className="flex justify-between items-center">
                        <span className="text-[10px] font-black text-gray-800 truncate max-w-[150px]" title={email.subject}>
                          {email.subject}
                        </span>
                        <span className={`text-[8px] font-black uppercase px-1.5 py-0.5 rounded-full tracking-wider border ${
                          isSent 
                            ? 'bg-emerald-50 text-emerald-700 border-emerald-100' 
                            : 'bg-amber-50 text-amber-700 border-amber-100'
                        }`}>
                          {isSent ? "Sent SMTP" : "Logged"}
                        </span>
                      </div>
                      
                      <p className="text-[10px] text-gray-500 font-semibold">
                        Recipients: <span className="text-gray-700 break-words">{email.to.join(", ")}</span>
                      </p>
                      
                      <div className="flex justify-between items-center pt-1 text-[9px] text-gray-400 font-bold border-t border-gray-150/40 mt-1">
                        <span>Date: {new Date(email.date).toLocaleString()}</span>
                        {email.error && <span className="text-rose-600 font-bold">Error: {email.error}</span>}
                      </div>
                    </div>
                  );
                })
              )}
            </div>
          </div>
        </div>

      </div>

    </div>
  );
}
